name: ETL Pipeline
run-name: Daily ETL Pipeline Run
env:
  PYTHON_VERSION: "3.10"
  AUTOMATION_USERNAME: "USERNAME"
  AUTOMATION_EMAIL: "USEREMAIL"

on:
  workflow_dispatch:
  schedule:
    - cron: "21 7 * * *"

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: ETL Pipeline
        env:
          OPENAQ_KEY: ${{ secrets.OPENAQ_KEY }}
        run: |
          python src/pipeline.py
      - name: Peek Data output
        run: |
          head -n 10 data/air_data.csv
      - name: Commit report
        run: |
          git config --global user.name "$AUTOMATION_USERNAME"
          git config --global user.email "$AUTOMATION_EMAIL"
          git add data/.
          git commit -m "Updating Data"
          git push
